[package]
name = "gstype"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-client = "0.30.1"
wayland-backend = "0.1.1"
wayland-scanner = "0.30.0"
